image: "alpine:3.7"
stages:
  - deploy

deploy:
  image:
    name: docker/compose:1.24.1
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - docker-compose build
    - docker-compose up -d
