image: "alpine:3.7"
stages:
  - deploy

variables:
  RELEASE_IMAGE: 183321040270.dkr.ecr.eu-central-1.amazonaws.com/covod-backend:latest

before_script:
  - docker login -u AWS -p $REGISTRY_TOKEN 183321040270.dkr.ecr.eu-central-1.amazonaws.com

deploy:
  image:
    name: docker/compose:1.24.1
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  only:
    refs:
      - master
  tags:
    - deploy
  script:
    - docker-compose build
    - docker-compose push
    - docker-compose up -d
