version: "3"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env.prod
    volumes:
      - db:/var/lib/postgresql/data

  covod:
    image: "${RELEASE_IMAGE}"
    restart: always
    env_file:
      - .env.prod
    volumes:
      - media:/app/media
    ports:
      - "127.0.0.1:22022:5000"

volumes:
  media:
  db: